### ISSUE TITLE
"dos" system does not show in the system list correctly...

### ISSUE THREAD

**Issue by vonmillhausen** [Vidnez/MinUArk#1]
Howdy! First of all, I love the theme! Nice and clean, and I especially love the SNES version, with just that splash of purple - looks great on my white RGB30!

When I set up the theme, one stock system that was showing "No Logo (request theme update)" was DOS games. In ArkOS for the RGB30, the ROM folder for DOS games is `dos`, however the defined _theme_ name for DOS games is `msdos`. Here's the relevant snippet from `es_systems.cfg` from my fully-up-to-date ArkOS RGB30:

```xml
	<system>
		<name>msdos</name>
		<fullname>Microsoft - DOS</fullname>
		<path>/roms2/dos/</path>
		<extension>.exe .EXE .com .COM .bat .BAT .conf .CONF .cue .CUE .iso .ISO .zip .ZIP .m3u .M3U .dosz .DOSZ</extension>
		<command>sudo perfmax %GOVERNOR% %ROM%; nice -n -19 /usr/local/bin/%EMULATOR% -L /home/ark/.config/%EMULATOR%/cores/%CORE%_libretro.so %ROM%; sudo perfnorm</command>
		   <emulators>
		      <emulator name="retroarch">
		 	<cores>
		 	  <core>dosbox_pure</core>
		 	  <core>dosbox</core>
		 	</cores>
		      </emulator>
		   </emulators>
		<platform>pc</platform>
		<theme>msdos</theme>
	</system>
```

You can see the `<theme>` is defined as `msdos`; renaming your `dos.svg` file to `msdos.svg` file fixed it for me.

Thanks again for the excellent theme! 😍

**Comment by Vidnez** [comment]
Hey, thanks for letting me know! I've updated the theme.
