### ISSUE TITLE
Cannot change the inactive text color

### ISSUE THREAD

**Issue by denizonm** [Vidnez/MinUArk#2]
I made a color scheme for the theme but for some reason I can't change the inactive text color.
I think it's hard coded to the themes.xml.

I managed to change the ones in the gamelists at least by changing the ffff90 values in the themes.xml to ${cgamelisttext} but i can't seem to get the ones in the main screen to change no matter what i do.

also this is deadass the best theme for the rgb30, thank you for making it.
I'm excited to share my color scheme when this is all sorted.

**Comment by Vidnez** [comment]
Yeah, theres no way to change the color (as far as I know) of selected and unselected items in the system carrusel.

I look forward to your new color scheme :)

**Comment by denizonm** [comment]
oh no :(
oh well.

I wonder why?
