### ISSUE TITLE
Theme not listed as available

### ISSUE THREAD

**Issue by elmimmo** [Vidnez/MinUArk#3]
On an RGB30 with ArkOS 2.0 (11272024), I place the unzipped `MinUArk-ArkOS` folder from the 3.0.2 release inside the TFGAME card, where I also have the games, as `/themes/MinUArk-ArkOS`, but the theme is not listed at ES settings ▸ UI Settings ▸ Theme. Any idea why? ES does find the games.

**Comment by Vidnez** [comment]
It has to go in `roms/themes/MinUArk-ArkOS`
